flash:
  notice: "alert-info"
  error: "alert-error"
  alert: "alert-warning"
  success: "alert-success"
  failed: "alert-danger"

default:
  date_format: 
    full: "%d %B, %Y"
    no_year: "%d/%m"
  
  task_color: "lightskyblue"
